INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (1, 'Agência Transfusional'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (2, 'Ala de pacientes críticos'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (3, 'Alojamento Canguru'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (4, 'Alojamento Conjunto'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (5, 'Ambulatório'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (6, 'Ambulatório adulto'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (7, 'Ambulatório especializado'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (8, 'Ambulatório infantil'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (9, 'Banco de Leite'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (10, 'Banco de Olhos'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (11, 'Banco de Sangue'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (12, 'Central de manipulação de medicamentos'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (13, 'Central de Transplantes e Captação de Órgãos'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (14, 'Centro Cirúrgico'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (15, 'Centro de Recuperação Pós-anestésica'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (16, 'Centro Obstétrico'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (17, 'Consultório'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (18, 'Coordenação administrativa'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (19, 'Coordenação assistencial'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (20, 'Diretoria'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (21, 'Emergência'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (22, 'Enfermaria'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (23, 'Enfermaria de Queimados'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (24, 'Farmácia' 	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (25, 'Laboratório'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (26, 'Laboratório Análises Clínicas'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (27, 'Núcleo de Epidemiologia'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (28, 'Nutrição Clínica'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (29, 'Nutrição Enteral'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (30, 'Nutrição Parenteral'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (31, 'Nutrição Produção'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (32, 'Posto de medicação'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (33, 'Sala de Parto'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (34, 'Sala de Pré-parto'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (35, 'Setor de Controle de Infecção Hospitalar'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (36, 'Setor de Quimioterapia'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (37, 'Triagem'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (38, 'Unidade Semi-intensiva'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (39, 'Unidade sem-intensiva'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (40, 'UTI Adulto'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (41, 'UTI Neonatal'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (42, 'UTI Obstétrica'	, now(), now());
INSERT INTO public.setores(id, nome, created_at, updated_at) VALUES (43, 'UTI Pediátrica'	, now(), now());
select setval('setores_id_seq', 43, true);
